#!/usr/bin/env python3
import sys
import os
import re
from PIL import Image
from PIL import ImageEnhance

# defaults: 0.65 and 2.5
BRIGHTNESS_FACTOR = 0.65
CONTRAST_FACTOR = 2.5


def single(filename):
    try:
        image = Image.open(filename)
    except FileNotFoundError:
        sys.exit("Could not find the given image file.")
    except OSError:
        sys.exit("Could not load the given image.")

    brightness = ImageEnhance.Brightness(image)
    image = brightness.enhance(BRIGHTNESS_FACTOR)

    contrast = ImageEnhance.Contrast(image)
    image = contrast.enhance(CONTRAST_FACTOR)

    # TODO: once this has been tested with a real scanned image, overwrite the original file
    image.save("edited-" + filename)


def all():
    image_count = 0
    files = os.listdir()
    for file in files:
        if re.search(".*([.](png|jpg|jpeg))$", file) is not None:
            image_count += 1
            print("Editing image " + str(image_count) + "...")
            single(file)
    if image_count == 0:
        print("No images found.")
    else:
        print("Done!")


if __name__ == "__main__":
    if len(sys.argv) > 2:
        print("Too many arguments. Specify an image file, or call with no arguments.")
    elif len(sys.argv) == 2:
        single(sys.argv[1])
    else:
        all()
